modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "CC0"

[[mods]]
modId = "adrenalin"
version = "${version}"
displayName = "Adrenalin Mod"
authors = "Sistr"
description = ""
#logoFile = ""

[[dependencies.adrenalin]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adrenalin]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adrenalin]]
modId = "architectury"
mandatory = true
versionRange = "[4.4.59,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.adrenalin]]
modId = "cloth-config"
mandatory = true
versionRange = "[6.2.62,)"
ordering = "AFTER"
side = "BOTH"